# Generated by Django 4.1.5 on 2023-01-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('name_user', models.CharField(max_length=30)),
                ('lastname_user', models.CharField(max_length=30)),
                ('number_user', models.IntegerField()),
                ('age_user', models.IntegerField()),
            ],
        ),
    ]
